import Foundation

/// Installs a tiny terminal shim that delegates to the app's private Python.
/// No Python packages are installed into the user's account; the shim merely
/// points at the already packaged interpreter and the updateable launcher in
/// Application Support.
struct TerminalInstaller {
    private let fileManager = FileManager.default

    func install(launcher: URL) throws -> URL {
        guard let resources = Bundle.main.resourceURL else {
            throw toolboxDesktopError.commandFailed("The app resource directory is unavailable.")
        }
        let python = resources.appendingPathComponent("python/bin/python3")
        guard fileManager.isExecutableFile(atPath: python.path) else {
            throw toolboxDesktopError.commandFailed("The bundled Python runtime is missing.")
        }

        let binDirectory = fileManager.homeDirectoryForCurrentUser.appendingPathComponent(".local/bin", isDirectory: true)
        try fileManager.createDirectory(at: binDirectory, withIntermediateDirectories: true)
        let command = binDirectory.appendingPathComponent("toolbox")

        // Double-quoted shell arguments require four characters to be escaped.
        // Doing it here allows application paths containing spaces to work and
        // prevents a path from being interpreted as shell syntax.
        func shellDoubleQuote(_ value: String) -> String {
            let escaped = value.reduce(into: "") { result, character in
                if ["\\", "\"", "$", "`"].contains(character) { result.append("\\") }
                result.append(character)
            }
            return "\"\(escaped)\""
        }

        let script = """
        #!/bin/sh
        # Generated by toolbox desktop.app. Reinstall from the app after moving it.
        export PYTHONDONTWRITEBYTECODE=1
        exec \(shellDoubleQuote(python.path)) \(shellDoubleQuote(launcher.path)) "$@"
        """
        try Data(script.utf8).write(to: command, options: .atomic)
        try fileManager.setAttributes([.posixPermissions: 0o755], ofItemAtPath: command.path)

        // Match install.sh by ensuring new zsh login shells can discover the
        // user-local command. Existing unrelated profile contents are retained.
        let profile = fileManager.homeDirectoryForCurrentUser.appendingPathComponent(".zprofile")
        let pathLine = "export PATH=\"$HOME/.local/bin:$PATH\""
        let existing = (try? String(contentsOf: profile, encoding: .utf8)) ?? ""
        if !existing.split(separator: "\n", omittingEmptySubsequences: false).contains(Substring(pathLine)) {
            let addition = "\n# Added by toolbox desktop.app\n\(pathLine)\n"
            if fileManager.fileExists(atPath: profile.path) {
                let handle = try FileHandle(forWritingTo: profile)
                try handle.seekToEnd()
                try handle.write(contentsOf: Data(addition.utf8))
                try handle.close()
            } else {
                try Data(addition.dropFirst().utf8).write(to: profile, options: .atomic)
            }
        }
        return command
    }

    /// Removes only a shim written by this app. A user may already have a
    /// Homebrew or hand-written command with the same name, and that belongs to
    /// them rather than to the desktop uninstaller.
    func uninstall() throws -> URL {
        let home = fileManager.homeDirectoryForCurrentUser
        let command = home.appendingPathComponent(".local/bin/toolbox")
        guard fileManager.fileExists(atPath: command.path) else {
            throw toolboxDesktopError.commandFailed("No app-installed command was found at \(command.path).")
        }
        let contents = try String(contentsOf: command, encoding: .utf8)
        guard contents.contains("Generated by toolbox desktop.app") else {
            throw toolboxDesktopError.commandFailed("The command at \(command.path) was not installed by this app, so it was left untouched.")
        }
        try fileManager.removeItem(at: command)

        // Remove the exact PATH block added during installation. If the PATH
        // line existed beforehand, install() never added this marked block.
        let profile = home.appendingPathComponent(".zprofile")
        if var profileText = try? String(contentsOf: profile, encoding: .utf8) {
            let addition = "\n# Added by toolbox desktop.app\nexport PATH=\"$HOME/.local/bin:$PATH\"\n"
            if profileText.contains(addition) {
                profileText = profileText.replacingOccurrences(of: addition, with: "\n")
                try profileText.write(to: profile, atomically: true, encoding: .utf8)
            }
        }
        return command
    }
}
